name = "my-cdn"
main = "index.js"
compatibility_date = "2023-12-01"

[vars]
# These link to the Secrets you added in GitHub Settings
CLIENT_ID = "REPLACE_ME_OR_USE_SECRETS"
CLIENT_SECRET = "REPLACE_ME_OR_USE_SECRETS"
REFRESH_TOKEN = "REPLACE_ME_OR_USE_SECRETS"
BASE_PATH = "/"

[site]
bucket = "./public" # Only if your repo has a public folder
